# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

puts 'Destroy services'
Service.destroy_all
puts 'Destroy services done'

puts 'Create services'

thermographie_batiment = Service.create!(name: 'Thermographie bâtiments', description: "La thermographie met en évidence les irrégularités dans l'isolation thermique des parois ou des toitures, identifie les ponts thermiques, détecte les défauts d'étanchéité à l'air, relève les infiltrations d'eau ou la présence d'humidité et, plus généralement, pointe du doigt tout ce qui relève de l'inconfort thermique.", Captation: 2.20, Traitement: 1.80, Déplacement: 0.94, infos1: "L'inspection thermique ou thermographie d'un bâtiment permet de :", infos2: "Visualiser les déperditions énergétiques, détecter les défauts ou l'absence d'isolation, visualiser les fuites d'air, trouver l'humidité dans l'isolation, les toits, les murs, dans la structure intérieure ou extérieure, identifier les ponts thermiques, repérer l'infiltration d'eau dans les toits terrasse, détecter les ruptures de canalisation d'eau chaude, observer les erreurs de construction, trouver les défauts dans les canalisations d'alimentation et le réseau de chauffage urbain.", infos3: "La thermographie s'intéresse au rayonnement émis par l'objet observé, puisque c'est de ce rayonnement que l'on déduit la température de l'objet. Elle enregistre l'intensité du rayonnement dans la partie infrarouge du spectre électromagnétique, et la convertit en image visible. Plus un objet est chaud, plus il émet du rayonnement infrarouge.", infos4: "La caméra thermique est le seul outil capable de produire une image des pertes énergétiques d'un bâtiment. Les images thermiques produites sont précises et convaincantes.", infos5: "WAIRDRONE vous propose une intervention comprenant une thermographie à 360° de votre bâtiment, ainsi que l'édition d'un rapport d'expertise thermique livré par voie dématérialisée au format PDF.", infos6: "Le rapport comprend une introduction, les informations de captation, une partie détaillant la toiture, une partie détaillant les différentes façades et menuiseries, une conclusion et nos recommandations.", infos7: "Chaque projet fera l'objet d'un devis personnalisé.", infos8: "Nous nous occupons de toutes les autorisations nécessaires, de la prise de contact avec les gestionnaires des espaces aériens aux validations avec les autorités compétentes.", infos9: "Nos solides partenariats avec plusieurs professionnels locaux compétents de la rénovation énergétique nous permettent de chiffrer au plus juste les rénovations envisagées et ainsi prioriser ces travaux.", infos10: "Une fois les rénovations effectuées, nous vous proposons une intervention complémentaire afin d'imager, contrôler et constater l'efficacité des travaux engagés.", logo: "https://res.cloudinary.com/wagui/image/upload/v1659606849/wairdrone/Logos/logo_th_b_s7woro.svg")
file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659360761/wairdrone/Thermographie/Thermo_3_pxo8li.jpg')
thermographie_batiment.photos.attach(io: file1, filename: 'thermographie_bâtiment.jpg', content_type: 'image/jpg')
file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562258/wairdrone/Thermographie/DJI_0189_R_mmv9qt.jpg')
thermographie_batiment.photos.attach(io: file2, filename: 'thermographie_bâtiment_2.jpg', content_type: 'image/jpg')
file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562272/wairdrone/Thermographie/DJI_0195_R_kba4jy.jpg')
thermographie_batiment.photos.attach(io: file3, filename: 'thermographie_bâtiment_3.jpg', content_type: 'image/jpg')
file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562255/wairdrone/Thermographie/DJI_0159_R_-_copie_a3lxve.jpg')
thermographie_batiment.photos.attach(io: file4, filename: 'thermographie_bâtiment_4.jpg', content_type: 'image/jpg')
file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562190/wairdrone/Thermographie/DJI_0001_R_1_xrsxbg.jpg')
thermographie_batiment.photos.attach(io: file5, filename: 'thermographie_bâtiment_5.jpg', content_type: 'image/jpg')
file6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562195/wairdrone/Thermographie/DJI_0031_R_1_za2h5r.jpg')
thermographie_batiment.photos.attach(io: file6, filename: 'thermographie_bâtiment_6.jpg', content_type: 'image/jpg')
file7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562194/wairdrone/Thermographie/DJI_0029_R_pxbpad.jpg')
thermographie_batiment.photos.attach(io: file7, filename: 'thermographie_bâtiment_7.jpg', content_type: 'image/jpg')
file8 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562294/wairdrone/Thermographie/DJI_0331_R_qswwne.jpg')
thermographie_batiment.photos.attach(io: file8, filename: 'thermographie_bâtiment_8.jpg', content_type: 'image/jpg')
file9 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562295/wairdrone/Thermographie/DJI_0293_R_sgudkw.jpg')
thermographie_batiment.photos.attach(io: file9, filename: 'thermographie_bâtiment_9.jpg', content_type: 'image/jpg')
file10 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562312/wairdrone/Thermographie/DJI_0349_R_-_copie_wmt890.jpg')
thermographie_batiment.photos.attach(io: file10, filename: 'thermographie_bâtiment_10.jpg', content_type: 'image/jpg')
file11 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562311/wairdrone/Thermographie/DJI_0561_R_pcrlxp.jpg')
thermographie_batiment.photos.attach(io: file11, filename: 'thermographie_bâtiment_11.jpg', content_type: 'image/jpg')
file12 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562308/wairdrone/Thermographie/DJI_0345_R_-_copie_cz6vf7.jpg')
thermographie_batiment.photos.attach(io: file12, filename: 'thermographie_bâtiment_12.jpg', content_type: 'image/jpg')
file13 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562307/wairdrone/Thermographie/Thermographie_toiture_nqnzlz.jpg')
thermographie_batiment.photos.attach(io: file13, filename: 'thermographie_bâtiment_13.jpg', content_type: 'image/jpg')
file14 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562305/wairdrone/Thermographie/Thermographie_toiture_3_jbocx4.jpg')
thermographie_batiment.photos.attach(io: file14, filename: 'thermographie_bâtiment_14.jpg', content_type: 'image/jpg')
file15 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562301/wairdrone/Thermographie/DJI_0479_R_u1ngmw.jpg')
thermographie_batiment.photos.attach(io: file15, filename: 'thermographie_bâtiment_15.jpg', content_type: 'image/jpg')
file16 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562274/wairdrone/Thermographie/DJI_0215_R_xckmgd.jpg')
thermographie_batiment.photos.attach(io: file16, filename: 'thermographie_bâtiment_16.jpg', content_type: 'image/jpg')
file17 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562274/wairdrone/Thermographie/DJI_0283_R_-_copie_o0oemw.jpg')
thermographie_batiment.photos.attach(io: file17, filename: 'thermographie_bâtiment_17.jpg', content_type: 'image/jpg')
file18 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562272/wairdrone/Thermographie/DJI_0203_R_v5oog3.jpg')
thermographie_batiment.photos.attach(io: file18, filename: 'thermographie_bâtiment_18.jpg', content_type: 'image/jpg')
file19 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562236/wairdrone/Thermographie/DJI_0147_R_uvevbf.jpg')
thermographie_batiment.photos.attach(io: file19, filename: 'thermographie_bâtiment_19.jpg', content_type: 'image/jpg')
file20 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659562220/wairdrone/Thermographie/DJI_0045_R_ksdx7b.jpg')
thermographie_batiment.photos.attach(io: file20, filename: 'thermographie_bâtiment_20.jpg', content_type: 'image/jpg')
file100 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659606849/wairdrone/Logos/logo_th_b_s7woro.svg')
thermographie_batiment.photos.attach(io: file100, filename: 'logo_thermographie_bâtiment.svg', content_type: 'image/svg')

puts "#{Service.count} services created"

thermographie_pv = Service.create(name: 'Thermographie photovoltaïque', description: 'Le drone est le moyen le plus rapide et le plus économique pour contrôler et diagnostiquer les panneaux photovoltaïques par thermographie, en réalisant des images thermiques.', Captation: 2.20, Traitement: 1.80, Déplacement: 0.94, infos1:"
Le moindre disfonctionnement invisible à l’œil nu, d’une cellule photovoltaïque, d’un raccordement ou autres est immédiatement repéré par les images infrarouges, faisant apparaitre les écarts de température par une différence des couleurs.", infos2: "Nos interventions peuvent être effectuées à réception/livraison définitive d’une installation neuve surtout si l’on désire en vérifier la qualité et les éventuelles faiblesses  (peut servir à tranquilliser le client sur la qualité de l’installation et garantir un état déterminé lors de l’installation)", infos3: " Une thermographie photovoltaïque permet de conserver une trace dans le temps de l’empreinte thermique et donc de l’efficacité de ses panneaux (peut servir à déterminer si des panneaux ne doivent pas être désactivés car leur performance est trop mauvaise par rapport aux autres)", infos4: "Nos interventions peuvent être programmées à la demande d’un poseur de panneau afin de trouver plus vite un panneau défectueux par thermographie", infos5: "La cellule chaude, source et risque : C’est une cellule avec un vice de construction ou mal placée ou qui a pris l’eau voire fendue. Sa chaleur est due au fait que la chaleur n’est non seulement plus convertie en électricité mais en plus, il se produit une inversion de polarité qui la transforme en une sorte de condensateur.", infos6: "Le motif thermique est l’aspect global des panneaux, étant généralement tous orientés de la même manière, ils doivent réagir de manière similaire et leur échauffement se ressembler. La seule différence est qu’il existe un sens de branchement dans un string et son départ est plus froid que son arrivée. Donc si le motif thermique n’est pas cohérent, c’est qu’il ya des problèmes de connexions dans certains panneaux ou entre eux.", infos7: "L'assurance qualité est d'une importance fondamentale pour les panneaux photovoltaïques. Ces panneaux doivent fonctionner sans défaillance pour être efficaces dans la production d'électricité, atteindre une grande durée de vie et apporter un retour sur investissement élevé. Pour écarter les défaillances, il faut évaluer les performances des panneaux par une méthode rapide, simple et fiable, à la fois pendant la production et après l'installation.", infos8: "L'utilisation des caméras thermiques pour l'évaluation des panneaux photovoltaïques présente plusieurs avantages. Les anomalies sont clairement visibles sur l'excellente image thermique et, contrairement à la plupart des autres méthodes, l'examen des panneaux installés est possible au cours de leur fonctionnement normal. Enfin, les caméras thermiques permettent de visualiser  de grandes surfaces en peu de temps.", infos9: "Chaque projet fera l'objet d'un devis personnalisé.", infos10: "Conclusion L'inspection thermographique des systèmes photovoltaïques permet de localiser rapidement les défauts possibles au niveau des cellules et des modules, ainsi que les éventuels problèmes de connexion. Elle est menée dans les conditions normales de fonctionnement et ne nécessite pas la mise à l'arrêt.", logo: "https://res.cloudinary.com/wagui/image/upload/v1659606854/wairdrone/Logos/logo_th_pv_yfwg7d.svg")
file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659366066/wairdrone/Thermographie_PV/Thermographie_photovolta%C3%AFque_nibgb8.jpg')
thermographie_pv.photos.attach(io: file1, filename: 'thermographie_pv.jpg', content_type: 'image/jpg')
file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614853/wairdrone/Thermographie_PV/DJI_0182_xn3ipr.jpg')
thermographie_pv.photos.attach(io: file2, filename: 'thermographie_pv2.jpg', content_type: 'image/jpg')
file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614693/wairdrone/Thermographie_PV/DJI_0183_R_ckqs3c.jpg')
thermographie_pv.photos.attach(io: file3, filename: 'thermographie_pv3.jpg', content_type: 'image/jpg')
file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659366066/wairdrone/Thermographie_PV/Thermographie_photovolta%C3%AFque_nibgb8.jpg')
thermographie_pv.photos.attach(io: file4, filename: 'thermographie_pv4.jpg', content_type: 'image/jpg')
file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659615195/wairdrone/Thermographie_PV/IMG_20211118_112637_nh1lqx.jpg')
thermographie_pv.photos.attach(io: file5, filename: 'thermographie_pv5.jpg', content_type: 'image/jpg')
file6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614855/wairdrone/Thermographie_PV/DJI_0176_rhsaua.jpg')
thermographie_pv.photos.attach(io: file6, filename: 'thermographie_pv6.jpg', content_type: 'image/jpg')
file7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614709/wairdrone/Thermographie_PV/DJI_0185_R_rdwx6m.jpg')
thermographie_pv.photos.attach(io: file7, filename: 'thermographie_pv7.jpg', content_type: 'image/jpg')
file8 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659615061/wairdrone/Thermographie_PV/WAIRDRONE_intervention_jjbbbx.jpg')
thermographie_pv.photos.attach(io: file8, filename: 'thermographie_pv8.jpg', content_type: 'image/jpg')
file9 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659615027/wairdrone/Thermographie_PV/IMG_20211118_111800_qspsox.jpg')
thermographie_pv.photos.attach(io: file9, filename: 'thermographie_pv9.jpg', content_type: 'image/jpg')
file10 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614931/wairdrone/Thermographie_PV/IMG_20211118_111747_zbbm4q.jpg')
thermographie_pv.photos.attach(io: file10, filename: 'thermographie_pv10.jpg', content_type: 'image/jpg')
file11 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614856/wairdrone/Thermographie_PV/DJI_0184_c8e0ce.jpg')
thermographie_pv.photos.attach(io: file11, filename: 'thermographie_pv11.jpg', content_type: 'image/jpg')
file12 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659615192/wairdrone/Thermographie_PV/IMG_20211118_112507_u2rnoy.jpg')
thermographie_pv.photos.attach(io: file12, filename: 'thermographie_pv12.jpg', content_type: 'image/jpg')
file13 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614848/wairdrone/Thermographie_PV/DJI_0174_zzup4q.jpg')
thermographie_pv.photos.attach(io: file13, filename: 'thermographie_pv13.jpg', content_type: 'image/jpg')
file14 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614678/wairdrone/Thermographie_PV/Capture_2_nu5tjg.jpg')
thermographie_pv.photos.attach(io: file14, filename: 'thermographie_pv14.jpg', content_type: 'image/jpg')
file15 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614845/wairdrone/Thermographie_PV/DJI_0168_v5hvrl.jpg')
thermographie_pv.photos.attach(io: file15, filename: 'thermographie_pv15.jpg', content_type: 'image/jpg')
file16 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614702/wairdrone/Thermographie_PV/DJI_0169_R_mmcoet.jpg')
thermographie_pv.photos.attach(io: file16, filename: 'thermographie_pv16.jpg', content_type: 'image/jpg')
file17 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614709/wairdrone/Thermographie_PV/DJI_0185_R_rdwx6m.jpg')
thermographie_pv.photos.attach(io: file17, filename: 'thermographie_pv17.jpg', content_type: 'image/jpg')
file18 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659620083/wairdrone/Thermographie_PV/DJI_0003_gtkys4.jpg')
thermographie_pv.photos.attach(io: file18, filename: 'thermographie_pv18.jpg', content_type: 'image/jpg')
file19 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659620057/wairdrone/Thermographie_PV/DJI_0002_R_syrbpt.jpg')
thermographie_pv.photos.attach(io: file19, filename: 'thermographie_pv19.jpg', content_type: 'image/jpg')
file20 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659620055/wairdrone/Thermographie_PV/DJI_0002_R_-_copie_cjkxos.jpg')
thermographie_pv.photos.attach(io: file20, filename: 'thermographie_pv20.jpg', content_type: 'image/jpg')
file100 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659606854/wairdrone/Logos/logo_th_pv_yfwg7d.svg')
thermographie_pv.photos.attach(io: file100, filename: 'logo_thermographie_pv.svg', content_type: 'image/svg')

puts "#{Service.count} services created"

pg = Service.create(name: 'Photogrammétrie', description: 'La solution WAIRDRONE pour la documentation de vos projets et pour le suivi de chantier !', Captation: 0.28, Traitement: 0.12, Déplacement: 0.94, infos1: "Documentez toutes les étapes de votre projet, suivez les progrès du site par rapport au calendrier projet, mesurez et contrôlez les dessins de conception et la construction afin de détecter rapidement tout écart ou erreur, obtenez une imagerie régulière de votre chantier et coordonnez les équipes du projet.", infos2: "", infos3: "INSPECTION : Inspections rapides et sécurisées. Visualisez les détails des infrastructures de différents angles à partir d'une imagerie haute définition. Obtenez une imagerie des zones difficiles d'accès par les méthodes traditionnelles. Mesure des volumes et calcul des quantités pour les opération de coupes et de remplissage. Obtenez des levés topographiques précis.",infos4: "ORTHOPHOTOGRAPHIE 2D : Mis à l'échelle et géoréférencée, couleurs véritables, compatibles avec les principaux logiciels de Conception Assistée par Ordinateurs (CAO) pour une représentation générale se la scène. LIVRABLES : .tif, .kml, .html", infos5: "NUAGE DE POINTS 3D : Couleurs véritables issues des images, coordonnées X, Y, Z pour un positionnement précis, compatibles avec les principaux logiciels de Conception Assistée par Ordinateurs (CAO). LIVRABLES : .las, .laz, .xyz, .ply", infos6: "MAILLAGE TEXTURÉ 3D : Idéal pour la visualisation. Utile pour la communication. LIVRABLES : .obj, .ply, .dxf, .fbx, .pdf", infos7: "EXEMPLES VIDÉO UTILISATION NUAGE DE POINTS DANS LOGICIELS CAO : https://youtu.be/px7TDSO1cgo et https://youtu.be/AUSFDKncmJw", infos8: "COURBES DE NIVEAU : Utiles en phase de conception et de terrassement. Représentation simplifiée de la surface du sol. LIVRABLES : .shp, .dxf, .pdf", infos9: "CARTE D'ÉLÉVATION 2D : Représentation de la hauteur et de la profondeur. LIVRABLES : .tif, .las, .laz, .xyz", infos10: "Chaque projet fera l'objet d'un devis personnalisé.", logo: "https://res.cloudinary.com/wagui/image/upload/v1659606849/wairdrone/Logos/logo_pg_o3xxls.svg")
file1 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659366318/wairdrone/Photogramm%C3%A9trie/Capture_3_yrhkmt.jpg')
pg.photos.attach(io: file1, filename: 'pg.jpg', content_type: 'image/jpg')
file2 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659366318/wairdrone/Photogramm%C3%A9trie/Capture_3_yrhkmt.jpg')
pg.photos.attach(io: file2, filename: 'pg_2.jpg', content_type: 'image/jpg')
file3 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614228/wairdrone/Photogramm%C3%A9trie/Capture_d_%C3%A9cran_Rancy4_riidp7.png')
pg.photos.attach(io: file3, filename: 'pg_3.jpg', content_type: 'image/jpg')
file4 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659615198/wairdrone/Photogramm%C3%A9trie/Building_edited_tufjm2.jpg')
pg.photos.attach(io: file4, filename: 'pg_4.jpg', content_type: 'image/jpg')
file5 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614202/wairdrone/Photogramm%C3%A9trie/Courbes_de_niveau_c6zlv1.jpg')
pg.photos.attach(io: file5, filename: 'pg_5.jpg', content_type: 'image/jpg')
file6 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614189/wairdrone/Photogramm%C3%A9trie/Capture_d_%C3%A9cran_Rancy7_mnt1od.png')
pg.photos.attach(io: file6, filename: 'pg_6.jpg', content_type: 'image/jpg')
file7 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614221/wairdrone/Photogramm%C3%A9trie/MNS_scdaep.jpg')
pg.photos.attach(io: file7, filename: 'pg_7.jpg', content_type: 'image/jpg')
file8 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614224/wairdrone/Photogramm%C3%A9trie/Capture_d_%C3%A9cran_les_3_croix_1_hibaia.png')
pg.photos.attach(io: file8, filename: 'pg_8.jpg', content_type: 'image/jpg')
file9 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614228/wairdrone/Photogramm%C3%A9trie/Ortho_DAP_2_dazfec.jpg')
pg.photos.attach(io: file9, filename: 'pg_9.jpg', content_type: 'image/jpg')
file10 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614203/wairdrone/Photogramm%C3%A9trie/Contrainte_d_%C3%A9chelle_yceqov.jpg')
pg.photos.attach(io: file10, filename: 'pg_10.jpg', content_type: 'image/jpg')
file11 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614181/wairdrone/Photogramm%C3%A9trie/Calcul_volume_terrassement_nrkyci.jpg')
pg.photos.attach(io: file11, filename: 'pg_11.jpg', content_type: 'image/jpg')
file12 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614165/wairdrone/Photogramm%C3%A9trie/Photogramm%C3%A9trie_Ch%C3%A2teaudouble_1_skjkze.jpg')
pg.photos.attach(io: file12, filename: 'pg_12.jpg', content_type: 'image/jpg')
file13 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614228/wairdrone/Photogramm%C3%A9trie/Ortho_DAP_2_dazfec.jpg')
pg.photos.attach(io: file13, filename: 'pg_13.jpg', content_type: 'image/jpg')
file14 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614228/wairdrone/Photogramm%C3%A9trie/Inspection_e75alo.jpg')
pg.photos.attach(io: file14, filename: 'pg_14.jpg', content_type: 'image/jpg')
file15 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659366318/wairdrone/Photogramm%C3%A9trie/Capture_3_yrhkmt.jpg')
pg.photos.attach(io: file15, filename: 'pg_15.jpg', content_type: 'image/jpg')
file16 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614228/wairdrone/Photogramm%C3%A9trie/Inspection_e75alo.jpg')
pg.photos.attach(io: file16, filename: 'pg_16.jpg', content_type: 'image/jpg')
file17 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614164/wairdrone/Photogramm%C3%A9trie/Sorties_kgrm1m.jpg')
pg.photos.attach(io: file17, filename: 'pg_17.jpg', content_type: 'image/jpg')
file18 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614246/wairdrone/Photogramm%C3%A9trie/Capture_d_%C3%A9cran_Rancy6_ambjsn.png')
pg.photos.attach(io: file18, filename: 'pg_18.jpg', content_type: 'image/jpg')
file19 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659366318/wairdrone/Photogramm%C3%A9trie/Capture_3_yrhkmt.jpg')
pg.photos.attach(io: file19, filename: 'pg_19.jpg', content_type: 'image/jpg')
file20 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659614163/wairdrone/Photogramm%C3%A9trie/Photogramm%C3%A9trie_Ch%C3%A2teaudouble_6_zvomp7.jpg')
pg.photos.attach(io: file20, filename: 'pg_20.jpg', content_type: 'image/jpg')
file100 = URI.open('https://res.cloudinary.com/wagui/image/upload/v1659606849/wairdrone/Logos/logo_pg_o3xxls.svg')
pg.photos.attach(io: file100, filename: 'logo_pg.svg', content_type: 'image/svg')

puts "#{Service.count} services created"
